wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  volumes:
    - ~/wordpress/wp_html:/var/www/html
  ports:
    - 8080:80
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: Abcd1234
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: Abcd1234